### ISSUE TITLE
Vitis: Unable to (force) compile when creating Plateform Component

### ISSUE THREAD

**Issue by capopaul** [corna/com.github.corna.Vivado#12]
Hello,

I had an issue with Vitis and I finally found a fix. Since I don't really know where to share it for other people, I found that here could be a good place.

---

**Issue**:

- Open vivado, create a project, make some design and export your hardware design with a .xsa file
- Opening vitis,
- Open the project's workspace
- Create Plateform Component
- In Hardware Design (XSA) select your .xsa file
- Then click next 

And at the step Select Operating System and Processor, I had this error:
`Error: Error in generating Processor List. [ERROR]: unable to (force) compile ['/home/paul/.var/app/com.github.corna.Vivado/data/xilinx-install/Vitis/2023.2/bin/dtc', '-b', '0', '-@', '-i', '/home/paul/Documents/Xilinx/edt_zcu102/.rigel_lopper_temp_platform/edt_zcu102_wrapper/hw/sdt', '-o', '/home/paul/Documents/Xilinx/edt_zcu102/.rigel_lopper/system-top.dts.dtb', '-I', 'dts', '-O', 'dtb', '/home/paul/Documents/Xilinx/edt_zcu102/.rigel_lopper/system-top.dts.pp', '-f']`

I closed the windows,

---

**Understand the problem**:

In Vitis I click Open a terminal, then just next to my terminal I have "Output"
There are the logs of my actions:

```
11:17:59 INFO  : bash, -c, source /home/paul/.var/app/com.github.corna.Vivado/data/xilinx-install/Vitis/2023.2/tps/lnx64/lopper-1.1.0/env/bin/activate && lopper -O /home/paul/Documents/Xilinx/edt_zcu102/.rigel_lopper -f -i /home/paul/.var/app/com.github.corna.Vivado/data/xilinx-install/Vitis/2023.2/tps/lnx64/lopper-1.1.0/env/lib/python3.8/site-packages/lopper/lops/lop-cpulist.dts /home/paul/Documents/Xilinx/edt_zcu102/.rigel_lopper_temp_platform/edt_zcu102_wrapper/hw/sdt/system-top.dts && deactivate
11:18:01 ERROR : [ERROR]: unable to (force) compile ['/home/paul/.var/app/com.github.corna.Vivado/data/xilinx-install/Vitis/2023.2/bin/dtc', '-b', '0', '-@', '-i', '/home/paul/Documents/Xilinx/edt_zcu102/.rigel_lopper_temp_platform/edt_zcu102_wrapper/hw/sdt', '-o', '/home/paul/Documents/Xilinx/edt_zcu102/.rigel_lopper/system-top.dts.dtb', '-I', 'dts', '-O', 'dtb', '/home/paul/Documents/Xilinx/edt_zcu102/.rigel_lopper/system-top.dts.pp', '-f']
11:18:01 INFO  :          /home/paul/.var/app/com.github.corna.Vivado/data/xilinx-install/Vitis/2023.2/bin/dtc: error while loading shared libraries: libyaml-0.so.2: cannot open shared object file: No such file or directory
11:18:01 INFO  : 
11:18:01 ERROR : Error in generating Processor List.
11:18:01 ERROR : Error in generating Processor List. [ERROR]: unable to (force) compile ['/home/paul/.var/app/com.github.corna.Vivado/data/xilinx-install/Vitis/2023.2/bin/dtc', '-b', '0', '-@', '-i', '/home/paul/Documents/Xilinx/edt_zcu102/.rigel_lopper_temp_platform/edt_zcu102_wrapper/hw/sdt', '-o', '/home/paul/Documents/Xilinx/edt_zcu102/.rigel_lopper/system-top.dts.dtb', '-I', 'dts', '-O', 'dtb', '/home/paul/Documents/Xilinx/edt_zcu102/.rigel_lopper/system-top.dts.pp', '-f']
```

I understood that libyaml-0.so.2 is not installed.

---

**Fix**:

Let's install that lib !
- `apt-get install libyaml-0.so.2` told me it is already installed
- Indeed when I did `dpkg -L libyaml-0-2` I have been able to find libyaml-0.so.2.0.6 in my lib folder

So it is on my computer but not in the vivado sandbox
- `cd $(flatpak info -l com.github.corna.Vivado)`
- `cd files/lib`
In this folder there is not libyaml-0.so.2.0.6 so I just copied it from my lib folder
- `sudo cp /usr/lib/x86_64-linux-gnu/libyaml-0.so.2 ./libyaml-0.so.2`

I also did the same process with libyaml-0.so.2.0.6
It solved my problem.

---

It is the first time I post an issue and give a solution with it, so please feel free to tell me if I should put this message on a more appropriate channel.

**Comment by corna** [comment]
Quite a late reply, I know.

Thanks for the info!

However, a flatpak package is expected to contain all the dependencies, which are either part of the "runtime" (i.e., the "base" of flatpak apps) or shipped as part of the package. Since libyaml is not part of the GNOME runtime but it is required by dtc, it should be shipped by this package.
I have added it to the next release, thanks again.
