### ISSUE TITLE
Implementation for versal chips requires gmake in the path

### ISSUE THREAD

**Issue by pftbest** [corna/com.github.corna.Vivado#15]
It's possible gcc and/or other build tools are required too
```
INFO: [Common 17-83] Releasing license: Implementation
921 Infos, 2446 Warnings, 8 Critical Warnings and 1 Errors encountered.
write_device_image failed
ERROR: [Common 17-70] Application Exception: Not found in path: gmake
INFO: [Common 17-206] Exiting Vivado at Sun Oct 20 17:12:21 2024...
```

**Comment by corna** [comment]
`make` is available, which is GNU make
All the build tools are already present
Can you try to add a symlink to `/usr/bin/make`, call it `gmake` and add it to the PATH to see if it works?

**Comment by pftbest** [comment]
I added gmake symlink in /usr/bin on the host system, however it didn't help. It's still missing inside the flatpack container. Not sure how to add it there, it says "Readonly filesystem". Can you please share a bit more details how to change the PATH for a flatpack app?

**Comment by pftbest** [comment]
Ok, so I found a workaround like this:
```bash
cd /var/lib/flatpak/app/com.github.corna.Vivado/x86_64/stable/1ed4e0cc94663f115d4fc28d0d5fc0ef6321628b6434cca04e24580016267f26/files/bin
ln -s /usr/bin/make gmake
```
And now generate device image works fine.

**Comment by corna** [comment]
Can you test [this build](https://github.com/flathub/com.github.corna.Vivado/pull/9) and let me know if it works?

**Comment by pftbest** [comment]
@corna it works

**Comment by corna** [comment]
Thanks
