### ISSUE TITLE
Version selection

### ISSUE THREAD

**Issue by yashi** [corna/com.github.corna.Vivado#2]
Is there a way to select old version of Vivado to install?

I just tried this Flatpak Vivado wrapper and it works great.  Thank you for your work!

I now have version 2021.1 installed.  And I realized that I have a design with 2020.1 and would like to use 2020.1 to keep working on it.  How can I install an old version with this?

**Comment by corna** [comment]
Sure, simply run `flatpak run --command=xilinx_install com.github.corna.Vivado` and install another Vivado version. Each time you run Vivado, a popup will ask you which version you want to use.

Note that the Xilinx API expose the download link only for the latest Vivado version, so you will have to manually provide the old installer when asked.
