### ISSUE TITLE
$HOME/.Xilinx

### ISSUE THREAD

**Issue by yashi** [corna/com.github.corna.Vivado#3]
I just found out that I have `~/.Xilinx/` after auto-installed using flatpak wrapper.  There is `.Xilinx/xinstall/xinstall_1634630342179.log` with today's timestamp.

So, is this norm? I thought it provides sand-boxing?

**Comment by corna** [comment]
Sorry for the very late reply, somehow the notifications for this project were disabled.

It is sandboxed, however `~/.Xilinx` is explicitly [exposed to the sandbox](https://github.com/corna/com.github.corna.Vivado/blob/master/com.github.corna.Vivado.yml#L15), as it contains logs and the license files. I will add a note in the README.md file though, thank you for reporting it.
