### ISSUE TITLE
Automatic download from xilinx.com broken

### ISSUE THREAD

**Issue by ciandonovan** [corna/com.github.corna.Vivado#4]
`download_vivado.py` fails to generate `token_cookie` from supplied username and password in function `get_auth_token`

```
Traceback (most recent call last):
  File "/app/share/xilinx/download_vivado.py", line 116, in <module>
    token = get_auth_token(args.username, password)
  File "/app/share/xilinx/download_vivado.py", line 54, in get_auth_token
    token_cookie = next(filter(lambda c: c.name == "token", cj))
StopIteration
```

The URL `https://www.xilinx.com/bin/public/webinstall/sso/authenticator` which is used by `download_vivado.py` to generate a token, with credentials passed as a GET request, currently returns `Error 405 Method Not Allowed` for any attempt.

It seems like Xilinx have updated or changed their public web API?

**Comment by corna** [comment]
Sorry for not fixing this earlier, somehow I had the notifications disabled for this repo.

Fixed in dd4aaacd416dbd303ba22aa9e7c2d910481e50e7
