### ISSUE TITLE
Zenity not found

### ISSUE THREAD

**Issue by nikAizuddin** [corna/com.github.corna.Vivado#5]
I'm having issues with installation on Fedora 35 because `zenity` is not installed:
```
flatpak run --command=zenity com.github.corna.Vivado
```

Got error:
```
bwrap: execvp zenity: No such file or directory
```

**Comment by corna** [comment]
Yes, zenity had been removed from the Gnome 41 runtime.

Fixed in f90252ff8685d58ddd38cd106d8248aa1ccc025a
