### ISSUE TITLE
Xilinx login term ambiguity

### ISSUE THREAD

**Issue by ciandonovan** [corna/com.github.corna.Vivado#7]
The user is prompted to enter their username and password for Xilinx, however in Xilinx's login flow they use the terminology "email" instead of "username" as the account identifier.
Users can sometimes second-guess themselves when asked for a username instead of an email, and won't enter an email in the username field since they'd assume if it was an email that was looked for - an email would be asked for.
Especially since any login auth failure is signaled by the same "unknown authentication error" message, the user isn't given a hint that they could simply be using their truncated email (without domain suffix) as a username erroneously, and instead might think there's a problem with their password or account in general.
Changing the nomenclature s/username/email would, I think, really polish off the already great UX

**Comment by corna** [comment]
I've replaced "username" with "e-mail" in 9f027d9, plus an additional fix to return better error messages.

Thanks for the suggestions!
