### ISSUE TITLE
install on secondary drive

### ISSUE THREAD

**Issue by ric96** [corna/com.github.corna.Vivado#8]
Hi, I use a comparatively small nvme for my main OS and data on a secondary drive. How can I install Vivado on that secondary drive?

I tried installing the flatpak on a custom path but that did not help, neither does manually changing the install path or creating a symlink to the secondary drive.

**Comment by corna** [comment]
You can change the installation path with `XILINX_INSTALL_PATH`. However, do not forget to also expose the corresponding path to flatpak.

You can use `flatpak override` to set it for all the subsequent runs. To do so, run (optionally with `--user` if you installed it as user):

```
flatpak override --env=XILINX_INSTALL_PATH=<YOUR_PATH> --filesystem=<YOUR_PATH> com.github.corna.Vivado
```

then install vivado.

Let me know if it works.

**Comment by corna** [comment]
I suppose it works, reopen if not.
